buildbot/buildbot-infra

host-vm1.yml, jail-buildbot.yml, local.yml
This is to address [TRAC-2850](http://trac.buildbot.net/ticket/2850).
=> configure buildbot.bb.net

roles/dns/templates/buildbot.net
This PR finalises the [task](http://trac.buildbot.net/ticket/2850#comment:15) for moving bb.bb.net off the flosoft machine.
=> point bb.bb.net A record to the right place

group_vars/all
It is quite useful when a set of packages needs to be moved between machines.
=> add rsync to utility package list

group_vars/all, host-service1.yml, host-service2.yml, host-service3.yml, host-vm1.yml, jail-bslave1.yml, jail-buildbot.yml, jail-docs.yml, jail-nine.yml, jail-ns1.yml, jail-www.yml, roles/sendmail/handlers/main.yml, roles/sendmail/tasks/main.yml
This also sets an alias for root.  I've updated this on service2, so we may see incoming cronspam from that host.
=> Configure sendmail for local mail delivery on all hosts and jails

roles/dns/tasks/main.yml, roles/dns/templates/224-255.128-255.10.211.140.in-addr.arpa, roles/dns/templates/named.conf.zones
This will require adding
```
224-255 NS c.ns.buddyns.com.
224-255 NS f.ns.buddyns.com.
224-255 NS ns1.he.net.
224-255 NS ns2.he.net.
$GENERATE 224-255 $ CNAME $.224-255
```
to the RTEMS zonefile for `128-255.10.211.140.in-addr.arpa`.  If that's not running BIND, then it looks more like
```
224-255 NS c.ns.buddyns.com.
224-255 NS f.ns.buddyns.com.
224-255 NS ns1.he.net.
224-255 NS ns2.he.net.
224 CNAME 224.224-255
225 CNAME 225.224-255
...
255 CNAME 255.224-255
```
(with the middle part filled in, of course).
This shouldn't require any change in the delegation from OSUOSL.  Note that I haven't set up the slave zones at buddyns and HE yet (I can't until ns1.bb.net is serving the zone).
@verm does this look right to you?
=> Add a delegated reverse zone for Buildbot's /27

jail-bot.yml, jail-ftp.yml, jail-lists.yml, jail-mx.yml, jail-mysql.yml, jail-syslog.yml, jail-trac.yml, local.yml, roles/base/defaults/main.yml, roles/base/tasks/syslog.yml
This adds just the 'base' role for all jails, which at the very least
means that they run Ansible regularly.  It carefully avoids configuring
a syslog loop on the syslog jail.
=> Manage all jails

jail-bslave1.yml, jail-buildbot.yml, jail-docs.yml, jail-lists.yml, jail-mx.yml, jail-nine.yml, jail-ns1.yml, jail-www.yml, roles/base/defaults/main.yml, roles/base/handlers/main.yml, roles/base/tasks/main.yml, roles/base/tasks/sendmail.yml, roles/sendmail/handlers/main.yml
Except on hosts that do explicit mail handling (lists, mx), where the
config is disabled.  This gets us the proper sendmail config on all of
the otherwise-unmanaged jails.
=> Configure sendmail in the 'base' role

jail-syslog.yml, roles/syslog-aggregator/handlers/main.yml, roles/syslog-aggregator/tasks/main.yml, roles/syslog-aggregator/templates/syslog-ng-buildbot.conf.j2, roles/syslog-aggregator/templates/syslog-ng.conf.j2, roles/syslog-aggregator/vars/main.yml
I've tested this in my local jail.  This will disable the existing syslog config on the production jail, then install and enable syslog-ng.
=> configure syslog server with syslog-ng

roles/dns/templates/buildbot.net
I just got an email from buddyns that we've used 180,000 queries so far this month (15 days).  That seems a bit high for the traffic that we get!  Increasing the TTL should allow more caching on resolving nameservers.
=> Set DNS TTLs to one day

roles/dns/templates/buildbot.net
We are hitting the 270kq limit in this, the shortest month of the year.
HE fixed things just after we switched away from them, and have been silently keeping up to date since, so I'm willing to go back.
=> Drop buddyns, which has a very low monthly query limit

roles/nginx/templates/static
SPDY can provide some nice speedups when using SSL that should help nine once SSL is enabled everywhere.
=> Enable SPDY when using SSL

roles/base/tasks/main.yml, roles/base/tasks/python-cert-symlink.yml
Python-2.7.9 now validates all certs, but it looks for its list of
recognized CAs in /etc/ssl/cert.pem, rather than under /usr/local.
See http://lists.freebsd.org/pipermail/freebsd-python/2015-January/007832.html
I added this link (via ln, not Ansible) on trac.buidlbot.net and it fixed the reCAPTCHA failures.
=> Make /etc/ssl/cert.pem exist for Python's benefit

jail-bslave1.yml
Plays are failing:
ERROR: Syntax Error while loading YAML script, /home/bbinfra/repo/jail-bslave1.yml 
Note: The error may actually appear before this position: line 59, column 5        
service_name: "{{ buildbot_net.slave_service_name }}"                            
service_dir: "{{ getent_passwd[worker_account].4 }}/{{ buildbot_net.bb_slave_name }}/{{ buildbot_net.bb_slave_dir }}"                                                 
^                                                                              
We could be wrong, but this one looks like it might be an issue with               
missing quotes.  Always quote template expression brackets when they               
start a value. For instance:                                                       
with_items: …
=> The line got outdented one level somehow

roles/nginx/tasks/main.yml, roles/nginx/templates/proxy, roles/nginx/templates/ssl.conf, roles/nginx/templates/static
The one part that was missing still for TLS were the proxied Buildbot instances. I moved the TLS configuration to a separate file so the static and proxy configurations won't drift.
=> Add TLS support to proxied sites

files/weekly-summary.py, jail-trac.yml
.. instead of dustin's desktop
This leaves the door open to send other emails from trac, too.  For
example, we could do a daily list of pull requests that are pending
review or merge, and which haven't been touched for, say, 24 hours.
See trac bug 3082
=> Send weekly status emails from the trac jail

jail-docs.yml
Unsure why these aren't in the virtualenv. The docs builder uses only `sphinxcontrib-blockdiag` and `docutils>=0.8` yet gets everything however this doesn't. These are the remaining packages and versions as of the latest docs build (#270 from today).
=> Add missing packages from the virtualenv

roles/nginx/tasks/main.yml, roles/vsftp/tasks/main.yml
The certificate changed but docs.buildbot.net still has the old certificate.
=> Restart the service when the certificate changes

roles/base/templates/run-ansible-pull.sh.j2
Ansible has a default of "localhost,<hostnames>,127.0.0.1" for the limit option. On docs, the hostnames includes "docs,docs.buildbot.net". The "docs" part is the issue. Not including it causes ansible to run successfully. Using the --limit option causes the default to be overriden so do that and construct it to drop the "docs" part.
Fixes ticket:3576, I think.
=> Set our own limit for ansible-pull

ansible.cfg
See http://trac.buildbot.net/ticket/3576#comment:3 for more details.
Short version is the `acls` option needs to be specified for the mount,
they aren't, so setfacl will fail.
This is a potential security issue, if untrusted people have access to
the temp files. Anything private would be in the jails where only people
with root have access at the moment so it's acceptable.
=> Allow world readable tmpfiles

roles/syslog-aggregator/templates/syslog-ng.conf.j2
This file worked fine for a long time, but puts syslog-ng in
compatibility mode, which apparently stopped working recently.
This is based on the freebsd default, but with some modifications.  The
new version is based on the default provided with the latest version
(3.7.3_4).
=> Update syslog-ng base config file

roles/simple-buildout/tasks/main.yml
If a buildout command fails, we want to retry it on the next run.  This
bumps the git repository back to the previous revision so that on the
next Ansible run it will change, and thus re-run the command.
=> Retry buildout commands that fail

roles/simple-buildout/tasks/main.yml
Simple cleanup as suggested by @seankelly in #137
=> Use the `|failed` filter instead of comparing rc

jail-docs.yml
The Makefile for docs calls 'python' so the python executable needs to be available to build docs.
=> Install python meta-package

group_vars/all, roles/dns/templates/224-255.128-255.10.211.140.in-addr.arpa, roles/dns/templates/buildbot.net
necessary for syslog.buildbot.net to be available.
note that internal only jails are also visible, but their ip address is not mapped, so that is not a very big issue.
=> generate named configuration from hosts config

roles/bb-master/tasks/main.yml, roles/elk/templates/oauth2_proxy.conf
syslog: properly set the cookie the the right domain (instead of local_ip default)
bb-master: properly store the github_token (instead of storing in json format, quoted)
=> fixes for prod:

group_vars/all
The IP was wrong in the hosts list.
=> Fix mysql jail IP

roles/bb-master/tasks/main.yml
This should fix the undefined errors in the buildbot jail. The issue is that Ansible is trying to access `github_oauth_keys['buildbot']` but that key doesn't exist. I opted for creating an empty file.
=> Use an empty default if no github oauth keys

roles/simple-buildout/tasks/main.yml
Currently Ansible fails with:
```
TASK [simple-buildout : Make sure we have an updated copy of the repository] ***
[WARNING]: Using world-readable permissions for temporary files Ansible needs
to create when becoming an unprivileged user which may be insecure. For
information on securing this, see https://docs.ansible.com/ansible/become.html
#becoming-an-unprivileged-user
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Local modifications exist in repository (force=no)."}
```
I assume there are somehow appeared changes in the working directory (maybe towncrier generated changelog in one of the previous builds).
With this PR changes in working directory will always be discarded.
=> discard modifications in git working directory

jail-nine.yml, roles/supervisor-service/templates/service.conf.j2
the master takes more time now to finish cleanly, but if supervisor kills it it won't restart it
=> increase supervisord stop timeout before it SIGKILLs

jail-nine.yml, roles/supervisor-service/templates/service.conf.j2
Let's try doing nine.bb.net CD again, in a less disruptive way.
=> use clean shutdown to manage nine.bb.net CD

roles/elk/templates/oauth2_proxy.conf
going through kibana proxy is much slower, so we change the conf
to allow direct access to elasticsearch
=> add direct access to elasticsearch

roles/vsftp/tasks/main.yml, roles/vsftp/templates/vsftpd.conf.j2
Use the same certificate and key that nginx uses. This should stop the cron emails from the ftp jail.
=> Fix vsftp TLS certificates

roles/base/templates/run-ansible-pull.sh.j2
The trac jail almost always complains about files that can't be deleted. The file list changes with every cron. Just filter them out completely.
=> Ignore "Permission denied" errors when clearing temp files

roles/user/defaults/main.yml, roles/user/tasks/main.yml
Some point after Ansible 2.1, the check changed and now a variable that has spaces in its value doesn't work. Explicitly compare against the empty string, and change the default to the empty string, to change the comparison to work.
Leaving the default value as nothing (e.g. "authorized_key:") has YAML use an empty dict as the value. Since the authorized_key is expected to be a string, use that as a default value.
=> Default authorized key to empty string and check it's not that

host-service1.yml, host-service2.yml
Note that these jails have their IPs specified in host_ips in
group_vars/all; the ip_address: .. format appears to be the old way,
previous to 90c8214ea54c251cbe073af49887f2859dc02e00.
Note, too, that this will lead to great sadness if service1 comes back up, as it will try to steal those IPs.  We will need to avoid that if the host ever does come back.
=> move jails on service1 to service2

group_vars/all
maybe we should install the full vim?
=> vim-lite renamed to vim-console

group_vars/all, jail-syslog.yml
We ran out of space on service1, mostly in the syslog jail.  I deleted `/var/log/logstash.log`, which was 17G, and that helped a little.  I restarted logstash too.
However, the bigger consumer of space is `/var/db/elasticache`.  What can we do to limit the size of that db?
=> elasticache is growing too big

roles/base/tasks/ansible-pull.yml, roles/base/tasks/packages.yml
This fixes a warning from Ansible:
[WARNING]: when statements should not include jinja2 templating delimiters such as {{ }} or {% %}. Found: {{ ansible_distribution == "FreeBSD" }}
=> Remove Jinja2 templating from when statements

roles/dns/templates/named.conf
We need to make sure we copy the old configs to the new Ansible setup when
service1 is back online.
=> Disable recursion in Bind.  This was requested by an OSL scanner.

group_vars/all, roles/dns/templates/224-255.128-255.10.211.140.in-addr.arpa, roles/dns/templates/buildbot.net
This includes conditionals so that forward/reverse for the www jail is
treated as `buildbot.net`, with `www` being a CNAME for that.
References #220 (and hopefully fixes?)
=> Include trailing `.` in reverse DNS, fix www -> buildbot.net

roles/elk/templates/logstash_events.conf
elastic do not like a high number of indices, as it loads all indices in memory from start
with low activity indexing like events, this makes no sense to create one index per day (default logstash)
=> limit number of indices in elastic

jail-www.yml
lockfile is managed in yarn, so npm install do not work anymore
Fixes: #47
=> jail-www: use yarn for build

roles/bb-master/tasks/main.yml
When master is crashed, curl will succeed, but the http code is 500, cause nginx is actually there
So we use the get_url ansible builtin instead of curl to be able
to easily get the status code
=> force update master if it is crashed

roles/bb-master/tasks/main.yml
Changes to buildbot-travis repository currently won't cause the service to be restarted to use newest version of the code.
=> bb-master: Restart buildbot service when buildbot-travis changes

roles/bb-master/tasks/main.yml
get_url does not treat /dev/null as a special file and tries to remove and rename on top of it.
This fixes failing ansible refresh in current production, at least when run from command line.
=> bb-master: Don't use /dev/null as destination for get_url

bootstrap.yml, group_vars/all, roles/jail/tasks/main.yml, roles/virtualenv3/tasks/main.yml, tox.ini, vagrant.yml
I updated service2 and service 3 to FreeBSD 13.0-RELEASE. That means they can access up-to-date packages, including Python 3 packages. Convert Ansible and `python2` references to running under Python 3.
=> Update Ansible version and convert to using Python 3

roles/elk/meta/main.yml, roles/elk/templates/elasticsearch.yml
The kibana5 and elasticsearch5 packages no longest exist. I picked the next available version for both, kibana6 and elasticsearch6. Some more work is still needed to get Elasticsearch working.
=> Update to Kibana 6 and Elasticsearch 6

roles/dns/tasks/main.yml
9.10 is no longer in FreeBSD repositories and thus playbook cannot proceed.
=> Upgrade bind to 9.16

roles/base/tasks/ansible-pull.yml, roles/base/templates/run-ansible-pull.sh.j2
Previously it was possible that multiple ansible-pull scripts were started concurrently (e.g. when one is failing due to timeout and retries repeatedly). Using flock avoids this issue.
=> Reliability fixes

roles/bb-master-docker/files/Dockerfile
This allows to push work in progress code and test it without merging to master.
=> bb-master-docker: Use metabuildbot branch from bb repository if exists

roles/nginx-proxy-letsencrypt/files/docker-compose.yml
This commit make certbot use buildbot.net instead of docs.buildbot.net as the name of identifier in its config and various paths.
=> Fix order of domains in certbot config

roles/base/tasks/ansible-pull.yml, roles/bb-master-docker/tasks/main.yml
Reverts buildbot/buildbot-infra#295
Turns out it's impossible to track infra repo state in git action because it's pulled by ansible pull already.
=> Revert "Track infra repo state"
