- host-vm1.yml
- jail-docs.yml
- local.yml
- roles/simple-buildout/README.rst
- roles/simple-buildout/defaults/main.yml
- roles/virtualenv/README.rst
- roles/virtualenv/defaults/main.yml
- roles/virtualenv/tasks/main.yml
[TRAC-2857](http://trac.buildbot.net/ticket/2857)
> Configure docs.bb.net

- localhost
- roles/base/tasks/ansible-pull.yml
- roles/base/templates/run-ansible-pull.sh.j2
This should fix [TRAC-3132](http://trac.buildbot.net/ticket/3132).  It runs under `env -i` anyway!
> run ansible-pull from the right dir, with HOME set

- roles/bb-master/tasks/main.yml
* buildbot refuses to upgrade if it's running
> stop supervisor service before upgrade

- roles/base/handlers/main.yml
- roles/base/tasks/ansible-pull.yml
- roles/base/templates/run-ansible-pull.sh.j2
Note that this will have bbinfra emailing us once an hour from each jail and service host.. well, hopefully.
> add an alias for bbinfra

- roles/dns/templates/buildbot.net
> Add forward DNS for internal hostnames

- roles/base/templates/run-ansible-pull.sh.j2
> only send email on failure (exit code 1)

- roles/dns/templates/buildbot.net
Add backup.int.buildbot.net to DNS (IP from email)
> add backup jail to DNS

- docs/network.txt
- host-service2.yml
- host-service3.yml
- host-vm1.yml
Fixes [TRAC-3160](http://trac.buildbot.net/ticket/3160)
> Migrate jails

- group_vars/all
- local.yml
- templates/track-config.sh
- track-config.yml
> Track configuration in local git repositories

- roles/base/templates/run-ansible-pull.sh.j2
Reverts buildbot/buildbot-infra#72
> Revert "only send email on failure (exit code 1)"

- roles/dns/templates/named.conf.zones
> New nameservers

- host-service1.yml
- host-service2.yml
- host-service3.yml
- local.yml
> Fix migrate jails

- roles/base/tasks/main.yml
- roles/base/tasks/periodic.yml
I feel like I've been deleting a lot of these lately!
> Make periodic quieter (Refs #3164)

- docs/upgrading-freebsd.txt
Add a file in docs containing the commands and some notes I took while upgrading the FreeBSD hosts.
> Add notes created during upgrading FreeBSD hosts

- jail-bslave1.yml
Quickly added another slave to the bslave1 jail. Probably isn't 100%. Just wanted to get something out there for review.
> Add buildbot.net slave to bslave1 jail

- host-service2.yml
- jail-supybot.yml
- local.yml
- roles/dns/templates/224-255.128-255.10.211.140.in-addr.arpa
- roles/dns/templates/buildbot.net
- roles/supybot/files/bb-supy.conf
- roles/supybot/files/meetingLocalConfig.py
- roles/supybot/tasks/main.yml
- roles/supybot/vars/main.yml
- templates/run-once
This is currently running in the supybot.buildbot.net jail.  Remaining to do:
* only restart the supervisord service when something changes (or maybe use a supybot command to reload)
* add a user (not sure this is necessary?)
* adjust the configuration to suit our needs
* install meetbot
> Initial Supybot install

- roles/supybot/handlers/main.yml
- roles/supybot/tasks/main.yml
I don't know if I got everything that should trigger a restart.
> Only restart supybot if something changes

- scripts/weekly_summary.py
> send status emails to new lists

- files/weekly-summary.py
Untested, but the syntax is correct at least..
> Weekly cleanup

- files/mergeable.py
- jail-trac.yml
I'll be turning off my own server soon, so this will be necessary
> send mergeable PR email from the trac jail, too

- jail-docs.yml
This now requires some extra packages, one of which depends on Pillow
which requires libjpeg.
Also, the Makefile requires GNU make.
@tardyp does this look good?
> Update the docs building process

- roles/base/templates/run-ansible-pull.sh.j2
Hopefully this will keep our github problem under control.
We still need to solve it, though -- after all, we pull the buildbot repo quite a lot on these hosts, too.
> Retry ansible-pull 10x

- jail-nine.yml
@rutsky let me know when this is good to land.  I'll need to do some hand-holding to get the DB upgrade done and whatnot.
> switch nine to use the bug2340 branch

- files/weekly-summary.py
This should get us up-to-date information for the weekly meeting.
> Include all changes up to the current day

- jail-nine.yml
since bug2340 branch is merged into master.
This reverts commit a15d90a3debdd2ac918a965f2a7fbe08d61562be.
> switch back to using master branch at nine.buildbot.net

- files/weekly-summary.py
> Also report metabbotcfg PRs in weekly report.

- roles/simple-buildout/tasks/main.yml
@tardyp @seankelly hopefully this should fix the errors on docs
> fix retries for simple buildout

- roles/admin-users/tasks/main.yml
- roles/base/tasks/packages.yml
- roles/bb-master/tasks/main.yml
- roles/packages/tasks/main.yml
- roles/simple-buildout/tasks/main.yml
- roles/virtualenv/tasks/main.yml
- track-config.yml
These are all of the deprecation warnings for bare variables found with a simple git-grep.
> Ansible 2.0 deprecated bare variables in with_* clauses

- jail-docs.yml
> Remove trailing colon

- group_vars/all
- roles/base/templates/run-ansible-pull.sh.j2
https://www.freebsd.org/cgi/man.cgi?query=timeout&sektion=1
> update ansible-pull to be time bound

- group_vars/all
- jail-events.yml
- roles/base/tasks/hosts.yml
- roles/base/tasks/main.yml
- roles/base/tasks/syslog.yml
- roles/base/templates/hosts.j2
- roles/elk/templates/logstash_syslog.conf
- put the /etc/hosts that amar wrote yesterday in conf
- remove reference from very old ip address (which is probably in the base jail)
> Syslog fixes and cleanup

- files/collectevents.py
- roles/elk/meta/main.yml
This allows to display cumulated data graphs like:
> add script to post process the data

- roles/nginx/templates/multiproxy
this should give big performance increase for big latency users
> improve the nginx config to enable http2

- roles/nginx/templates/proxy
> enable http2 for nginx proxy template

- roles/virtualenv/tasks/main.yml
should fix installation from GitHub
> install packages in non-editable mode

- local.yml
- roles/base/tasks/ansible-pull.yml
- roles/bb-master/tasks/main.yml
- roles/bb-slave/tasks/main.yml
- roles/dns/tasks/main.yml
- roles/elk/tasks/main.yml
- roles/simple-buildout/tasks/main.yml
- roles/supybot/tasks/main.yml
- roles/virtualenv/tasks/main.yml
- vm-build1.yml
Discovered ansible-lint to check various things about Ansible plays. Fixed a variety of small issues with the tasks.
> Ansible lint fixes

- files/weekly-summary.py
This could probably be done better with some searches (as it is, it downloads many more issues / PRs than it needs to), but for the moment this is working
> Include GH issues in summary, omit Trac

- jail-docs.yml
This makes sure we use the exact same method as the CI
> update docs building recipe to use requirements.txt

- ansible.cfg
- bootstrap.yml
- common.yml
- local.yml
- roles/AerisCloud.docker/tasks/RedHat.yml
- roles/AerisCloud.docker/tasks/main.yml
- roles/AerisCloud.docker/tasks/rh6.yml
- roles/base/tasks/main.yml
- roles/base/tasks/sendmail.yml
- roles/base/templates/run-ansible-pull.sh.j2
- roles/bb-master/tasks/main.yml
- roles/dns/tasks/main.yml
- roles/elk/tasks/main.yml
- roles/jail/tasks/main.yml
- roles/nginx/tasks/main.yml
- roles/simple-buildout/tasks/main.yml
- roles/ssh/tasks/main.yml
- roles/supervisor/tasks/main.yml
- roles/supybot/tasks/main.yml
- roles/syslog-aggregator/tasks/main.yml
- roles/vsftp/tasks/main.yml
- vagrant.yml
> Fix deprecation warnings

- roles/elk/meta/main.yml
- roles/elk/templates/elasticsearch.yml
upgrade of the db must be manual. :-(
> upgrade to elk5

- jail-docs.yml
change the venv name to make sure it gets recreated
> switch docs to python3

- jail-docs.yml
> setup en_US.UTF8 environment variable

- roles/postfix/files/virtusertable
> update sa2ajj's email

- roles/supervisor/tasks/main.yml
py27-supervisor is not working anymore
> switch to py37-supervisor

- group_vars/all
- roles/bb-master/files/install-master
- roles/bb-master/tasks/main.yml
Looks like buildbot startup was broken after FreeBSD upgrade.
See also https://github.com/buildbot/buildbot/pull/6122
> Fix buildbot startup

- group_vars/all
Fixes: e3ab570a187b47242bf24296f1add0d47bc60a0a
> Bump DNS serial

- roles/bb-master-docker/tasks/main.yml
Currently buildbot.buildbot.net instance restarts whenever it wants. This stops all builds running at the time and is inconvenient.
The cause for that is broken checks for busy master. This PR fixes that.
> Reliable restart

- roles/base/tasks/ansible-pull.yml
- roles/bb-master-docker/tasks/main.yml
This way docker containers will be rebuilt if infra repo state gets new commits
> Track infra repo state
